[package]
name = "rustpm_orm"
version = "0.3.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = "1.0.130"
serde_derive = "1.0.130"
sled = "0.34.7"


[dev-dependencies]
lazy_static = "1.4.0"